# This is a basic workflow to help you get started with Actions

name: Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main, master]
    paths:
      - 'functions/**'
      - '.github/workflows/server.yml'

defaults:
  run:
    working-directory: functions

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: ${{ github.ref }}-server
      cancel-in-progress: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Lint code
        run: bun run lint

      #      - name: Test code
      #        working-directory: functions
      #        run: npm run test:ci

      - name: Create .env file
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Deploy Cloud Functions
        run: bun x firebase deploy --only functions:translate --token "${{ secrets.FIREBASE_TOKEN }}"
